# Generated by Django 2.0.1 on 2018-01-17 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_auto_20180116_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='airdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 17, 22, 2, 53, 590668, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='voter.Season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='voter.Show'),
        ),
    ]
